### ISSUE TITLE
audio not working in Kodi Jarvis 16.1

### ISSUE THREAD

**Issue by punzilla** [shiznix/plugin.video.catchuptv.au.ten#1] opened 2019-09-11 02:56 UTC
I've downloaded and installed the add-on and was able to play the videos though can't hear any sound. This is using Android box Samsung homesync Android 4.2.2. Audio works elsewhere but not on the add-on.

**Comment by shiznix** [comment] 2019-09-11 13:22
Only guessing but maybe that old version of Kodi doesn't like the M3U8 playlist file presented to it (video and audio streams are separate in the playlist file and Kodi automatically manages mutliplexing).
Maybe try upgrading to the lastest stable Kodi 18 and see if that fixes.

**Comment by punzilla** [comment] 2020-04-25 01:05
Hi there, 
Since my previous bug report I had upgraded to Kodi 18 and have been using this plugin successfully for months. Now when selecting streams it no longer plays. I'm using Kodi 18.6 on my Nvidia Shield with Android 9. Please let me know if you require any type of logs, if there's anything you can do to address the issue that would be great. 
Thank you.

**Comment by shiznix** [comment] 2020-04-25 12:57
Glad it worked for you.

No logs necessary, am able to easily reproduce the problem and should be fairly trivial to fix shortly, thanks for the report :)

**Comment by shiznix** [comment] 2020-05-03 02:29
Oops spoke too soon - not so trivial after all.

10 are no longer serving their own basic M3U8 playlist files and have moved their content serving to https://fastly.net

Fastly serve M3U8 playlist files that reference AES-128 encrypted split MPEG-2 TS streams.
These M3U8 playlist files cannot be presented directly to Kodi for playing as we'd done previously.

Good news is that after doing some research it looks like Kodi's InputStream Adaptive addon can handle this type of encrypted M3U8 so that's the next thing to try.

**Comment by shiznix** [comment] 2020-05-03 21:52
Should be fixed in commit 3a2100db3d9c15cb5f9a80e4974b05d9ee48d084 , thanks :)

**Closed as completed by shiznix** 2020-05-03 21:52 UTC
